config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'who', to: 'pages#who'
  resources :sheeps do
      resources :bookings, only: [:new, :create]
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :sheep
  belongs_to :user
  validate :booking_validity

  private

  def booking_validity
    if sheep.bookings.present?
      errors.add(:end_date, "Already booked")
    end
  end
end

app/models/sheep.rb
class Sheep < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
   pg_search_scope :global_search,
     against: [],
     associated_against: {
      user: [ :address ]
      },
     using: {
       tsearch: { prefix: true } # <-- now `superman batm` will return something!
     }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :sheeps, dependent: :destroy
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
    after_action :verify_authorized, except: :index, unless: :skip_pundit?
    after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end


    # Uncomment when you *really understand* Pundit!
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(root_path)
    end

    private

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @sheep = Sheep.find(params[:sheep_id])
    @booking.sheep = @sheep
    authorize(@booking)
    if @booking.save
      @sheep.available = false
      @sheep.save
      redirect_to dashboard_path, notice: "Your sheep was successfully booked."
    else
      render "sheeps/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user_sheeps = current_user.sheeps
    @user_bookings = current_user.bookings

  end
end

app/controllers/sheeps_controller.rb
class SheepsController < ApplicationController
  before_action :set_sheep, only: [:show, :destroy, :edit, :update]
  skip_after_action :verify_policy_scoped, only: [:index]
  def index
    if params[:query].present?
      if params[:start_date].present? && params[:end_date].present?
        overlaping_bookings = Booking.where("start_date <= ? AND ? <= end_date", params[:end_date], params[:start_date])
        @sheeps = @sheeps.where.not(id: overlaping_bookings.pluck(:sheep_id))
      else
        @sheeps = Sheep.global_search(params[:query])
      end
    else
      @sheeps = policy_scope(Sheep)
    end

    @sheeps = @sheeps.geocoded
    @markers = @sheeps.group_by(&:latitude).map do |latitude,sheeps|
      {
        lat: sheeps.first.latitude,
        lng: sheeps.first.longitude,
        count: sheeps.size,
        infoWindow: render_to_string(partial: "info_window", locals: { sheeps: sheeps })
      }
    end

  end

  def show
    @booking = Booking.new
  end

  def destroy
    @sheep.destroy

    redirect_to sheeps_path
  end

  def new
    @sheep = Sheep.new
    authorize @sheep
  end

  def create
    @sheep = Sheep.new(sheep_params)
    authorize @sheep
    @sheep.user = current_user
    @sheep.address = current_user.address
    if @sheep.save
      redirect_to @sheep, notice: "Your sheep's card was successfully created."
    else
      render :new
    end
  end

  def edit
   @sheep = Sheep.find(params[:id])
  end


 def update
     if @sheep.update(sheep_params)
       redirect_to sheep_path(@sheep)
     else
       render :edit
     end
 end

  private

  def set_sheep
    @sheep = Sheep.find(params[:id])
    authorize @sheep
  end

  def sheep_params
    params.require(:sheep).permit(:nickname, :square_meter_per_hour,:price_per_day, :available, :photo)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Rent a sheep</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">

    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>

      <%= render 'shared/flashes' %>
      <%= render 'shared/navbar' %>
      <div class="page">
          <%= yield %>
      </div>
      <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>My dashboard</h1>
  <p>Welcome <%= current_user.first_name %> <%= link_to "Edit my Profil", edit_user_registration_path  %></p>
  <h2>My Sheeps</h2>
  <div class="row row-cols-1 row-cols-md-3">
    <% @user_sheeps.each do |sheep| %>
    <div class="col mb-4">
      <div class="card-sheep">
        <%if sheep.photo.attached?%>
        <%= link_to sheep_path(sheep) do %>
          <img src= '<%= cl_image_path sheep.photo.key, height: 300, width: 400, crop: :fill %>'>
          <% end %>
        <% end %>
        <div class="card-sheep-infos">
          <div>
            <h2><%= link_to sheep.nickname, sheep_path(sheep) %></h2>
            <p>Short description here!</p>
          </div>
          <span>
            <% if policy(sheep).destroy? %>
            <%= link_to sheep_path(sheep),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
            <i class="las la-trash-alt"></i>
            <% end %>
            <% end %>
          </span>
          <% sheep.bookings.each do |booking| %>
          <% if booking.end_date >= Date.today %>
            <p> Rented by <%= booking.user.first_name %> from <%= booking.start_date %> to <%= booking.end_date %> </p>
          <% end %>
        <% end %>
          <h2 class="card-sheep-pricing"><%= sheep.price_per_day %> €/Day</h2>
          <% if sheep.user.photo.attached? %>
            <%= cl_image_tag sheep.user.photo.key, height: 120, width: 120, crop: :fill, class:"card-trip-user avatar-bordered" %>
          <% else %>
            <img src='https://png.pngtree.com/png-vector/20191110/ourmid/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg' class="card-trip-user avatar-bordered"/>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

<% if @user_bookings.any? %>
  <h2>My Bookings</h2>
  <div class="row row-cols-1 row-cols-md-3">
    <%@user_bookings.each do |book| %>
    <div class="col mb-4">
      <div class="card-sheep">
        <%if book.sheep.photo.attached?%>
        <img src= '<%= cl_image_path book.sheep.photo.key, height: 300, width: 400, crop: :fill %>'>
        <% end %>
        <div class="card-sheep-infos">
          <div>
            <p>Name : <%= book.sheep.nickname %></p>
            <p>Owner : <%= book.sheep.user.first_name %></p>
            <p>Start date :<%= book.start_date %></p>
            <p>End date : <%= book.end_date %></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% else %>
  <p>No bookings yet</p>
<% end %>



</div>

app/views/pages/home.html.erb
<div id="home">
  <div class="welcome">
      <h1>
      <span id="banner-typed-text"></span>
      </h1>
  </div>



  <%= form_tag sheeps_path, method: :get do %>
    <span>Ville</span>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control-sheep",
      placeholder: "Find a sheep"
    %>
    <span>Date de début</span>
    <%= date_field_tag :start_date,
      params[:start_date],
      class: "form-control-date",
      placeholder: "Start date"
    %>
    <span>Date de fin</span>
    <%= date_field_tag :end_date,
      params[:end_date],
      class: "form-control-date",
      placeholder: "End date"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

  <div class="title">
    <h2><%= link_to "Check all our available Sheep  !", sheeps_path  %></h2>
  </div>


</div>

app/views/pages/who.html.erb
<div class="glogal ml-5 m-3">
    <h2>They rent our sheep a looooot !</h2>
    <a href="/dashboard">Return to your dashboard </a>


    <div class="flexbox" >

      <div id="carouselExampleIndicators" class="carousel slide mycarousel" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>

        </ol>

        <div class="carousel-inner row">

          <div class="carousel-item active">
            <img class="d-block w-100" src="https://avatars1.githubusercontent.com/u/59261819?s=460&v=4" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="https://ca.slack-edge.com/T02NE0241-USTMQQUCT-b8513b00ea1c-512" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="https://avatars0.githubusercontent.com/u/58769219?v=4" alt="Third slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="https://avatars3.githubusercontent.com/u/50374101?s=460&u=ee79a434fdd6a1d001644b6dc221670289e7102a&v=4" alt="Fourth slide">
          </div>

          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

      </div>
      <div class="text_who">

        <p>Hey guys, if you're here is that you're awsome and you've got a garden to cut!.</p>
        <p> Thanks to be bla bla bla</p>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <strong><%= link_to "Who are we ?", who_path %></strong>
    <strong>This footer is made with <i class="fas fa-heart"></i> at Le Wagon</strong>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "https://cdn0.iconfinder.com/data/icons/farm-and-agriculture/512/farm-15-512.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All Sheep", sheeps_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 120, width: 120, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://png.pngtree.com/png-vector/20191110/ourmid/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/sheeps/_form.html.erb
<%= simple_form_for(@sheep, method: :post, url: sheeps_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nickname %>
    <%= f.input :square_meter_per_hour %>
    <%= f.input :price_per_day %>
    <%= f.input :photo, as: :file %>
    <%= f.input :available %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sheeps/_info_window.html.erb
<% sheeps.each do |sheep| %>
  <h2><%= link_to sheep.nickname, sheep_path(sheep) %></h2>
  <p><%= sheep.description %></p>
<% end %>

app/views/sheeps/edit.html.erb
<div class="container edit-sheep">
  <%= simple_form_for(@sheep) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :nickname %>
      <%= f.input :square_meter_per_hour %>
      <%= f.input :price_per_day %>
      <%= f.input :photo, as: :file %>
      <%= f.input :available %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

  <%= link_to "Back to the sheep's card", @sheep %>
</div>

app/views/sheeps/index.html.erb
<div class="container">
  <h1>All sheeps</h1>
  <div>
    <% if policy(Sheep).create? %>
    <h5><%= link_to "Put my sheep on rent", new_sheep_path%></h5>
    <% end %>
  </div>
  <div class="row row-cols-1 row-cols-md-3">
    <% @sheeps.each do |sheep| %>
    <div class="col mb-4">
      <div class="card-sheep">
        <%= link_to sheep_path(sheep) do %>
        <% if sheep.photo.attached? %>
          <%= cl_image_tag sheep.photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <% end %>
        <div class="card-sheep-infos">
          <div>
            <h2><%= link_to sheep.nickname, sheep_path(sheep) %></h2>
            <p>Short description here!</p>
          </div>
          <span>
            <% if policy(sheep).destroy? %>
            <%= link_to sheep_path(sheep),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
            <i class="las la-trash-alt"></i>
            <% end %>
            <% end %>
          </span>
          <h2 class="card-sheep-pricing"><%= sheep.price_per_day %> €/Day</h2>
          <% if sheep.user.photo.attached? %>
            <%= cl_image_tag sheep.user.photo.key, height: 120, width: 120, crop: :fill, class:"card-trip-user avatar-bordered" %>
          <% else %>
            <img src='https://png.pngtree.com/png-vector/20191110/ourmid/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396.jpg' class="card-trip-user avatar-bordered"/>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

</div>

app/views/sheeps/new.html.erb
<div class="container new-sheep">
  <h1>Add a new sheep</h1>

  <%= render 'form', sheep: @sheep %>

  <%= link_to 'Back', sheeps_path %>
</div>

app/views/sheeps/show.html.erb
<div class="card container" style="width: 36rem;">
  <h5 class="card-title">
    <%= @sheep.nickname.capitalize %>

  </h5>
  <%= cl_image_tag @sheep.photo.key,class: "card-img-top",alt: "Card image cap" %>
  <div class="card-body">
     <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <% @sheep.bookings.each do |book| %>
        Booking by <%= book.user.first_name %>:
          <p>Start Date : <%= book.start_date %></p>
          <p>End Date : <%= book.end_date %></p>
        <% end %>
      </li>
    <li class="list-group-item">
      <p>
        Price : <%=@sheep.price_per_day %> euros per day
      </p>
    </li>
    <li class="list-group-item">
      <p>
        Can crop : <%=@sheep.square_meter_per_hour%> meters square per hour.
      </p>
    </li>
    <li class="list-group-item">
      <p> Belongs to : <%=@sheep.user.first_name%> </p>
    </li>
    <li class="list-group-item">
      <p>
        Address : <%=@sheep.user.address %>
      </p>
    </li>
  </ul>

    <p class="card-text">
      <% if !policy(@sheep).edit? %>
  <div>
    <%= simple_form_for([@sheep, @booking]) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :start_date, html5: true %>
      <%= f.input :end_date, html5: true %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
  </div>
<% end %>
  </div>

  <div class="card-body">
<!--     <a href="#" class="card-link">Card link</a> -->
    <% if policy(@sheep).edit? %>
      <%= link_to "Edit my sheep's card", edit_sheep_path, class: "card-link" %>
    <% end %>
    <%= link_to "Back to all sheeps", sheeps_path, class: "card-link" %>
  </div>
</div>